jobs:
  - job: 'BuildPelican'  # name of the job, no spaces allowed
    displayName: 'Pelican Build'  # friendly name to display in the UI
    continueOnError: false  # 'true' if future jobs should run even if this job fails; defaults to 'false'
    #variables: { string: string } | [ variable ]
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: git submodule update --init --recursive
      displayName: 'Updating Submodules'
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: pelican content -s publishconf.py 
      displayName: 'Pelican Build'
