jobs:
  - job: 'BuildPelican'  # name of the job, no spaces allowed
    displayName: 'Pelican Build'  # friendly name to display in the UI
    continueOnError: false  # 'true' if future jobs should run even if this job fails; defaults to 'false'
    #variables: { string: string } | [ variable ]
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: git submodule update --init --recursive
      displayName: 'Updating Submodules'
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: pelican content -s publishconf.py 
      displayName: 'Pelican Build'
    - task: CopyFiles@2
      inputs:
        sourceFolder: output # Optional
        #contents: '**' 
        targetFolder: $(Build.ArtifactStagingDirectory)
        cleanTargetFolder: true # Optional
        #overWrite: false # Optional
        #flattenFolders: false # Optional
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current' # Options: current, specific
        #project: # Required when buildType == Specific
        #pipeline: # Required when buildType == Specific
        #specificBuildWithTriggering: false # Optional
        #buildVersionToDownload: 'latest' # Required when buildType == Specific# Options: latest, latestFromBranch, specific
        #branchName: 'refs/heads/master' # Required when buildType == Specific && BuildVersionToDownload == LatestFromBranch
        #buildId: # Required when buildType == Specific && BuildVersionToDownload == Specific
        #tags: # Optional
        #downloadType: 'single' # Options: single, specific
        #artifactName: # Required when downloadType == Single
        itemPattern: '$(Build.ArtifactStagingDirectory)/**' # Optional
        downloadPath: '$(System.ArtifactsDirectory)' 
        #parallelizationLimit: '8' # Optional