language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make clean
- make publish
#- pelican -s publishconf.py -v
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: output
  target_branch: gh-pages
  on:
    branch: dev

notifications:
  webhooks:
    urls:
      - https://hooks.slack.com/services/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
    payload:
      - {"text": "This is a line of text in a channel.\nAnd this is another line of text."}

