language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make clean
- make publish
#- pelican -s publishconf.py -v
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: output
  target_branch: gh-pages
  on:
    branch: dev

notifications:
  slack: 
    rooms:
      - four51:$SLACK_TOKEN#kreeher
      - ordercloudapi:$OCSUPPORT_TOKEN#kreeher
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}"

